### ISSUE TITLE
Add support for `--add-host` when building an image

### ISSUE THREAD

**Issue by bradfordboyle** [concourse/oci-build-task#23]
I am looking at using this task to replace some tasks that I've written that use `docker/dind` for building Docker images. For some of our images we need to use the `--add-host` option of `docker build`.

Skimming the [code for buildkit](https://github.com/moby/buildkit/blob/d13c5afeda0eb336a5b11387ca13d89689606ddc/frontend/dockerfile/builder/build.go#L47), I _think_ this could be done with `--opt add-hosts=<host:ip>`. This is my first time looking at buildkit, so I may be entirely mistaken.

I suppose the simplest way to add this functionality is to check for a non-empty task param called `ADD_HOSTS`.

**Comment by bgandon** [comment]
Support for the `$BUILDKIT_ADD_HOSTS` environment variable has been added by #24 in Jan 2021 and shipped with version [v0.8.0](https://github.com/concourse/oci-build-task/releases/tag/v0.8.0) of this task in June 2021.

I've just contributed the documentation in #80 today.
